name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # Runs every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: j3oe
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
